<?php

namespace AppBundle\Entity;

/**
 * BloodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BloodRepository extends \Doctrine\ORM\EntityRepository
{
}
