<?php

namespace AppBundle\Entity;

/**
 * DataPersonalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataPersonalRepository extends \Doctrine\ORM\EntityRepository
{
}
